name: git actions demo
on: [push]
jobs:
  Actions_demo:
    runs-on: ubuntu-latest
    steps:
    - run: ls
    - name: Check out repo
      uses: actions/checkout@v3
    - run: ls
    - run: touch randomefile.txt
    - run: ls
