name: git actions demo
on: [push]
jobs:
  Actions_demo:
  runs-on: ubuntu-latest
  steps:
  - run: ls
  - run: pwd
  - run: touch randomefile.txt
  - run: ls
  - name: Check out repo
    uses: actions/checkout@v3
  
  - run: ls