name: git actions demo
on: [push]
env:
  NAME: Celio
  
jobs:
  Actions_demo:
    runs-on: ubuntu-latest
    steps:
    - run: ls
    - run: pwd
    - name: Check out repo
      uses: actions/checkout@v3
    - run: ls
    - run: touch randomefile.txt
    - run: ls
  
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - run: chmod +x buildScript.sh
    - run: ./buildScript.sh
    - run: ls

  build_job1:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - run: chmod +x buildScript1.sh
    - run: ./buildScript1.sh
    - run: ls  
